# Generated by Django 2.0.4 on 2018-05-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetDataDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField(unique=True)),
                ('total_money', models.IntegerField()),
                ('lottery_type', models.CharField(max_length=100)),
                ('lottery_period', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cdd_bet_report_day',
                'ordering': ('-report_date',),
            },
        ),
        migrations.CreateModel(
            name='ChannelDataDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('platform', models.IntegerField()),
                ('channel_id', models.IntegerField()),
                ('proxy_id', models.IntegerField()),
                ('proxy_type', models.IntegerField()),
                ('cps_data', models.IntegerField(default=0)),
                ('cpa_data', models.IntegerField(default=0)),
                ('cpd_data', models.IntegerField(default=0)),
                ('cpc_data', models.IntegerField(default=0)),
                ('cpm_data', models.IntegerField(default=0)),
                ('cps_rate', models.IntegerField(default=0)),
                ('cpa_price', models.IntegerField(default=0)),
                ('cpd_price', models.IntegerField(default=0)),
                ('cpc_price', models.IntegerField(default=0)),
                ('cpm_price', models.IntegerField(default=0)),
                ('pay_user', models.IntegerField(default=0)),
                ('order_count', models.IntegerField(default=0)),
                ('channel_fee', models.IntegerField(default=0)),
                ('coupon_fee', models.IntegerField(default=0)),
                ('charge_money', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cdd_channel_report_day',
                'ordering': ('-report_date',),
            },
        ),
        migrations.CreateModel(
            name='PayDataDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField(unique=True)),
                ('total_money', models.IntegerField()),
                ('pay_type', models.CharField(max_length=100)),
                ('srv_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cdd_pay_report_day',
                'ordering': ('-report_date',),
            },
        ),
        migrations.CreateModel(
            name='ProxyDataDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('platform', models.IntegerField()),
                ('proxy_id', models.IntegerField()),
                ('bd_id', models.IntegerField()),
                ('proxy_type', models.IntegerField()),
                ('cps_data', models.IntegerField(default=0)),
                ('cpa_data', models.IntegerField(default=0)),
                ('cpd_data', models.IntegerField(default=0)),
                ('cpc_data', models.IntegerField(default=0)),
                ('cpm_data', models.IntegerField(default=0)),
                ('cps_rate', models.IntegerField(default=0)),
                ('cpa_price', models.IntegerField(default=0)),
                ('cpd_price', models.IntegerField(default=0)),
                ('cpc_price', models.IntegerField(default=0)),
                ('cpm_price', models.IntegerField(default=0)),
                ('pay_user', models.IntegerField(default=0)),
                ('order_count', models.IntegerField(default=0)),
                ('channel_fee', models.IntegerField(default=0)),
                ('coupon_fee', models.IntegerField(default=0)),
                ('charge_money', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cdd_proxy_report_day',
                'ordering': ('-report_date',),
            },
        ),
        migrations.CreateModel(
            name='UserDataDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('platform', models.IntegerField()),
                ('channel_id', models.IntegerField()),
                ('proxy_id', models.IntegerField()),
                ('bd_id', models.IntegerField()),
                ('day1', models.IntegerField()),
                ('day3', models.IntegerField()),
                ('day7', models.IntegerField()),
                ('day15', models.IntegerField()),
                ('day30', models.IntegerField()),
                ('day60', models.IntegerField()),
                ('day90', models.IntegerField()),
                ('cps_data', models.IntegerField()),
                ('cpa_data', models.IntegerField()),
            ],
            options={
                'db_table': 'cdd_user_report_day',
                'ordering': ('-report_date',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='userdataday',
            unique_together={('report_date', 'platform', 'channel_id')},
        ),
    ]
