# Generated by Django 2.0.4 on 2018-05-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betdataday',
            name='report_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paydataday',
            name='report_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='betdataday',
            unique_together={('report_date', 'lottery_type', 'lottery_period')},
        ),
        migrations.AlterUniqueTogether(
            name='paydataday',
            unique_together={('report_date', 'pay_type', 'srv_name')},
        ),
    ]
