# Generated by Django 2.0.4 on 2018-06-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20180525_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsBetDataDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('total_money', models.IntegerField()),
                ('lottery_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cdd_sports_bet_report_day',
                'ordering': ('-report_date',),
            },
        ),
        migrations.RenameModel(
            old_name='BetDataDay',
            new_name='NumberBetDataDay',
        ),
        migrations.AlterModelTable(
            name='numberbetdataday',
            table='cdd_number_bet_report_day',
        ),
        migrations.AlterUniqueTogether(
            name='sportsbetdataday',
            unique_together={('report_date', 'lottery_type')},
        ),
    ]
