# Generated by Django 2.0.4 on 2018-06-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20180604_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyDataDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('platform', models.IntegerField()),
                ('proxy_id', models.IntegerField()),
                ('cps_data', models.IntegerField(default=0)),
                ('cpa_data', models.IntegerField(default=0)),
                ('cpd_data', models.IntegerField(default=0)),
                ('cpc_data', models.IntegerField(default=0)),
                ('cpm_data', models.IntegerField(default=0)),
                ('cps_rate', models.IntegerField(default=0)),
                ('cpa_price', models.IntegerField(default=0)),
                ('cpd_price', models.IntegerField(default=0)),
                ('cpc_price', models.IntegerField(default=0)),
                ('cpm_price', models.IntegerField(default=0)),
                ('pay_user', models.IntegerField(default=0)),
                ('order_count', models.IntegerField(default=0)),
                ('proxy_fee', models.IntegerField(default=0)),
                ('coupon_fee', models.IntegerField(default=0)),
                ('charge_money', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cdd_proxy_report_day',
                'ordering': ('-report_date',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='proxydataday',
            unique_together={('report_date', 'platform', 'proxy_id')},
        ),
    ]
