# Generated by Django 2.0.4 on 2018-06-05 14:29

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proxy_id', models.IntegerField()),
                ('commission', models.IntegerField(default=0)),
                ('is_used', models.IntegerField(default=0)),
                ('h5_url', models.CharField(default='', max_length=255)),
                ('android_url', models.CharField(default='', max_length=255)),
                ('ios_url', models.CharField(default='', max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('mark', models.CharField(default='', max_length=255)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cdd_channel_info',
                'ordering': ('-add_time',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Commerce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bd_name', models.CharField(max_length=100)),
                ('bd_id', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=1)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cdd_bd_info',
                'ordering': ('-add_time',),
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proxy_name', models.CharField(default='', max_length=100)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
                ('qq', models.CharField(default='', max_length=20)),
                ('bd_id', models.IntegerField(default=0)),
                ('proxy_level', models.IntegerField(default=0)),
                ('proxy_type', models.IntegerField(default=0)),
                ('commission', models.IntegerField(default=0)),
                ('pay_type', models.IntegerField(default=1)),
                ('real_name', models.CharField(default='', max_length=100)),
                ('bank_account', models.CharField(default='', max_length=100)),
                ('bank_name', models.CharField(default='', max_length=100)),
                ('bank_number', models.CharField(default='', max_length=100)),
                ('bank_addr', models.CharField(default='', max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cdd_proxy_info',
                'ordering': ('-add_time',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
