# Generated by Django 2.0.4 on 2018-06-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='android_url',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='h5_url',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='ios_url',
        ),
    ]
