# Generated by Django 2.0.4 on 2018-06-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_auto_20180611_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='channel_name',
            new_name='real_name',
        ),
    ]
