# Generated by Django 2.0.4 on 2018-06-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('role_id', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cdd_admin',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField(default=0)),
                ('key', models.CharField(default='-', max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('name', models.CharField(default='', max_length=100)),
                ('url', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cdd_admin_permission',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='AdminRelevance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_id', models.IntegerField(default=0)),
                ('permission_gather', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'cdd_admin_relevancerolepre',
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cdd_admin_role',
                'ordering': ['-add_time'],
            },
        ),
    ]
