# Generated by Django 2.0.4 on 2018-06-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminPermission',
            new_name='Permission',
        ),
        migrations.RenameModel(
            old_name='AdminRole',
            new_name='Role',
        ),
        migrations.RenameModel(
            old_name='AdminRelevance',
            new_name='RolePermission',
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['add_time']},
        ),
        migrations.AlterModelTable(
            name='permission',
            table='cdd_permission',
        ),
        migrations.AlterModelTable(
            name='role',
            table='cdd_role',
        ),
        migrations.AlterModelTable(
            name='rolepermission',
            table='cdd_role_permission',
        ),
    ]
