# Generated by Django 2.0.4 on 2018-06-18 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20180618_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolepermission',
            old_name='permission_gather',
            new_name='permission',
        ),
    ]
