# Generated by Django 2.0.4 on 2018-06-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20180619_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolepermission',
            old_name='permission',
            new_name='permissions',
        ),
    ]
