# Generated by Django 2.0.4 on 2018-06-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_auto_20180619_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
