# Generated by Django 2.0.4 on 2018-06-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_auto_20180620_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='admin_type',
        ),
    ]
